E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from  django.conf import settings
from django.conf.urls.static import static
from.import views
from .views import bikash_payment_view
from admin_app import urls as amdin_app_urls

from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', views.Master, name='master'),
    path('', views.Index, name='index'),
    path('', include(app_urls)),
    path('', include(amdin_app_urls)),


    path('signup', views.signup,name='signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),


    #contct page
    path('contact_us', views.Contact_Page, name='contact_page'),

    #checkout page
    path('checkout/', views.submit_payment_request, name='checkout'),

    #order page
    path('order/', views.Your_Order, name = 'order'),


    #product Page
    path('product/', views.Product_page, name='product'),

    #product_detail
    path('product/<str:id>', views.Product_detail, name='product_detail'),

    path('accounts/', views.Account_details, name='accounts'),

    path('ferthosi/', views.Ferthosi, name='ferthosi'),
    path('payment/', views.payment_view, name='payment'),

    path('bikash-payment/', views.bikash_payment_view, name='bikash_payment'),
    path('payment-request/', views.payment_request_view, name='payment_request'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment-confirmation/', views.payment_confirmation_view, name='payment_confirmation'),
    path('submit-payment-request/', views.submit_payment_request, name='submit_payment_request'),
              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E_shop/admin_app/urls.py
from django.urls import path


app_name = 'authority'

# Views

from admin_app import manage_order
from admin_app import admin_main

urlpatterns = [
    path('authority/', admin_main.AdminHomeView.as_view(), name='authority'),
    path('logout/', manage_order.UserLogout.as_view(), name='logout'),
    
]

# # manage set menu
# urlpatterns += [
#     path('add-set-menu-food/', manage_foods.AddMenuFoodView.as_view(), name='add_set_menu_food'),
#     path('update-set-menu-food/<int:pk>/', manage_foods.UpdateMenuFoodView.as_view(), name='update_set_menu_food'),
#     path('delete-set-menu-food/<int:pk>/', manage_foods.DeleteMenuFoodView.as_view(), name='delete_set_menu_food'),
#     path('add-set-menu/', manage_foods.AddFoodsView.as_view(), name='add_set_menu'),
#     path('update-set-menu/<int:pk>/', manage_foods.UpdateFoodsView.as_view(), name='update_set_menu'),
#     path('delete-set-menu/<int:pk>/', manage_foods.DeleteFoodsView.as_view(), name='delete_set_menu'),
    
# ]

# # Manage Table
# urlpatterns += [
#     path('table-booking-request/', manage_table.TableBookingRequestListView.as_view(), name='table_bookig_request_list'),
#     path('table-booked-list/', manage_table.TableBookedListView.as_view(), name='table_booked_list'),
#     path('table-booking-details/<int:pk>/', manage_table.TableBookingDetailsView.as_view(), name='table_bookig_details'),
#     path('table-booking-confirm/<int:pk>/', manage_table.ConfirmTableBookingView.as_view(), name='table_bookig_confirm'),
#     path('table-booking-delete/<int:pk>/', manage_table.DelteBookTableView.as_view(), name='table_bookig_delete'),
#     path('table-report/', manage_table.TableReportView.as_view(), name='table_report'),
# ]


# # manage admin settings
# urlpatterns += [
#     path('add-food-category/', admin_settings.AddFoodCategoryView.as_view(), name='add_food_category'),
#     path('update-food-category/<int:pk>/', admin_settings.UpdateFoodCategoryView.as_view(), name='update_food_category'),
#     path('delete-food-category/<int:pk>/', admin_settings.DeleteFoodCategoryView.as_view(), name='delete_food_category'),
#     path('add-shipping-charge/', admin_settings.AddShippingChargeView.as_view(), name='add_shipping_charge'),
#     path('update-shipping-charge/<int:pk>/', admin_settings.UpdateShippingChargeView.as_view(), name='update_shipping_charge'),
#     path('Customer-message/', admin_settings.CustomerMessageView.as_view(), name='customer_message'),
#     path('Customer-message-detail/<int:pk>/', admin_settings.CustomerMessageDetailView.as_view(), name='customer_message_detail'),
# ]

# Manage Order
urlpatterns += [
    path('pending-order-list/', manage_order.PendingListView.as_view(), name='pending_order_list'),
    path('confirmed-order-list/', manage_order.ConfirmedOrderListView.as_view(), name='confirmed_order_list'),
    path('order-details/<int:pk>/',  manage_order.OrderDetailsView.as_view(), name='order_details'),
    path('order-confirm/<int:pk>/',  manage_order.ConfirmOrderView.as_view(), name='order_confirm'),
    path('order-delete/<int:pk>/',  manage_order.DeleteOrderView.as_view(), name='order_delete'),
    path('order-report/',  manage_order.ConfirmedOrderListReportView.as_view(), name='order_report'),
    path('confirm_delevery/<int:pk>/',  manage_order.ConfirmDeleveryView.as_view(), name='confirm_delevery'),
    
]

E_shop/app/urls.py
from django.urls import path

# Views
from app.views import add_to_cart
from app.views import increase_cart_item
from app.views import decrease_cart_item
from app.views import remove_form_cart
from app.views import ChartProductListView
from app.views import check_out
from app.views import payment
from app.views import complete_payment
from app.views import purchase
from app.views import MyOrderListView

app_name = 'app'



# manage order
urlpatterns = [
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('cart-details/', ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/', increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/', decrease_cart_item, name='decrease_cart'),
    # path('my-order/', manage_order.MyOrderListView.as_view(),name="my_order"),
]

urlpatterns += [
    path('checkout/', check_out, name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-success/', complete_payment, name='payment_success'),
    path('purchase/<val_id>/<tran_id>/', purchase, name='purchase'),
    path('my-order/', MyOrderListView.as_view(),name="my_order"),
]

E_shop/admin_app/models.py
from django.db import models

# Create your models here.

E_shop/admin_app/forms.py
from django import forms

from app.models import Order

class ConfirmDeleveryForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('delevery_status',)


class OrderConfirmForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('order_confirm',)

E_shop/admin_app/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect
from datetime import datetime

# Permission Classes
from django.contrib.auth.mixins import LoginRequiredMixin

# Generic Classes
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import UpdateView
from django.views.generic import DeleteView


# Models 
from app.models import Order
from app.models import ShippingCharge

# Forms
from admin_app.forms import ConfirmDeleveryForm
from admin_app.forms import OrderConfirmForm

from admin_app.filters import OrderFilter

from admin_app.permissions import AdminPassesTestMixin

class PendingListView(LoginRequiredMixin, AdminPassesTestMixin, ListView):
    model = Order
    queryset = Order.objects.filter(ordered=True, order_confirm=False).order_by('-id')
    context_object_name = 'orders'
    template_name = 'authority/order_details.html'

    def get_context_data(self, **kwargs):
        print('Query Set: ',self.queryset)
        context = super().get_context_data(**kwargs)
        context["title"] = "Pending Order List" 
        return context

class ConfirmedOrderListView(LoginRequiredMixin, AdminPassesTestMixin, ListView):
    model = Order
    queryset = Order.objects.filter(ordered=True, order_confirm=True).order_by('-id')
    context_object_name = 'orders'
    template_name = 'authority/order_details.html'

    def get_context_data(self, **kwargs):
        print('Query Set: ',self.queryset)
        context = super().get_context_data(**kwargs)
        context["title"] = "Confirmed Order List" 
        context["form"] = ConfirmDeleveryForm
        context["confirmed"] = True 
        return context


class OrderDetailsView(LoginRequiredMixin, AdminPassesTestMixin, DetailView):
    model = Order
    context_object_name = 'order'
    template_name = 'authority/order_details.html'

    def get_context_data(self, **kwargs):
        shipping_charge = ShippingCharge.objects.latest('id')
        order_total = Order.objects.filter(id=self.kwargs['pk'])[0]
        context = super().get_context_data(**kwargs)
        context["title"] = 'Order Details' 
        context["details"] = True
        context["shipping_charge"] = shipping_charge
        context["total"] = order_total.get_totals()+shipping_charge.shipping_charge
        return context

class ConfirmOrderView(LoginRequiredMixin, AdminPassesTestMixin, UpdateView):
    model = Order
    form_class = OrderConfirmForm
    template_name = 'authority/order_details.html'
    success_url = reverse_lazy('authority:table_bookig_details', kwargs={'pk': 0})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Confirm Table Booking Request"
        return context
    
    def form_valid(self, form):
        if form.is_valid():
            form_obj = form.save(commit=False)
            form_obj.confirmed_at = datetime.now()
            form_obj.save()
        messages.success(self.request, "Order Accepted Successfully")
        self.success_url = reverse_lazy('authority:order_details', kwargs={'pk': self.object.id})
        return super().form_valid(form)
    
class ConfirmDeleveryView(LoginRequiredMixin, AdminPassesTestMixin, UpdateView):
    model = Order
    form_class = ConfirmDeleveryForm
    template_name = 'authority/order_details.html'
    success_url = reverse_lazy('authority:confirmed_order_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Confirm Table Booking Request"
        return context
    
    def form_valid(self, form):
        if form.is_valid():
            form_obj = form.save(commit=False)
        messages.success(self.request, "Food Delevery Successfully")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Something wrong try again!")
        return super().form_invalid(form)


class DeleteOrderView(LoginRequiredMixin, AdminPassesTestMixin, DeleteView):
    model= Order
    context_object_name ='order'
    template_name = 'authority/order_details.html'
    success_url = reverse_lazy('authority:confirmed_order_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete order Table" 
        context["deleted"] = True
        return context

class ConfirmedOrderListReportView(LoginRequiredMixin, AdminPassesTestMixin, ListView):
    model = Order
    queryset = Order.objects.filter(ordered=True, order_confirm=True).order_by('-id')
    filterset_class = OrderFilter
    template_name = 'authority/order_report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Confirmed Order List"
        context["orders"] = self.filterset_class(self.request.GET, queryset=self.queryset)
        return context

E_shop/admin_app/templates/authority_base/authority_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'assests/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'assests/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'assests/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'assests/css/sizzling.css' %}" rel="stylesheet">

    <!-- font-aswome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/ddee993d4e.js" crossorigin="anonymous"></script>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    

</head>

<body>
    <div class="container-fluid position-relative bg-dark d-flex p-0">
        {% comment %} <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End --> {% endcomment %}


        <!-- Sidebar Start -->
        <div class="sidebar bg-primary pe-4 pb-3">
            <nav class="navbar bg-primary navbar-primary">
                <a href="{% url 'authority:authority' %}" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-white"><i class="fa-solid fa-burger text-white me-2"></i>E<span class="text-dark">SHOPER</span></h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{{request.user.profile.photo.url}} " alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0"> {{request.user.profile.first_name}} {{request.user.profile.last_name}}</h6>
                        <span>Admin</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a href="{% url 'authority:authority' %}" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
    
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa-solid fa-burger me-2"></i>Order</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'authority:pending_order_list' %}" class="dropdown-item"><i class="fa-solid fa-burger me-2"></i>Pending Order</a>
                            <a href="{% url 'authority:confirmed_order_list' %}" class="dropdown-item"><i class="fa-solid fa-burger me-2"></i>Confirmed Order</a>
                        </div>
                    </div>
                    
                   
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content bg-dark">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                {% comment %} <form class="d-none d-md-flex ms-4">
                    <input class="form-control border-0" type="search" placeholder="Search">
                </form> {% endcomment %}
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        {% comment %} <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a> {% endcomment %}
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        {% comment %} <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a> {% endcomment %}
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src=" {{request.user.profile.photo.url}} " alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex"> {{request.user.profile.first_name}}  {{request.user.profile.last_name}} </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="{% url 'authority:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <div class="container">
                {% if messages %}
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" {% endif %}>
                            <i class="fa fa-exclamation-circle me-2"></i>{{ message }}!
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}    
            </div>

            <div class="container-fluid pt-4 px-4">
                <div class="row bg-light rounded align-items-center mx-0">
                    {% block body %}
            
            
                    {% endblock body %}
                </div>
            </div>

            
            {% block footer %}

                 <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Sizzling Station</a>, All Right Reserved. 
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="iubat.edu">IUBAT</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
            
            {% endblock footer %}

           

     
        </div>
        <!-- Content End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assests/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'assests/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'assests/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'assests/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assests/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'assests/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'assests/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'assests/js/main.js' %}"></script>
</body>

</html>