E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from  django.conf import settings
from django.conf.urls.static import static
from.import views
from .views import bikash_payment_view
from admin_app import urls as amdin_app_urls

from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', views.Master, name='master'),
    path('', views.Index, name='index'),
    path('', include(app_urls)),
    path('', include(amdin_app_urls)),


    path('signup', views.signup,name='signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),


    #contct page
    path('contact_us', views.Contact_Page, name='contact_page'),

    #checkout page
    path('checkout/', views.submit_payment_request, name='checkout'),

    #order page
    path('order/', views.Your_Order, name = 'order'),


    #product Page
    path('product/', views.Product_page, name='product'),

    #product_detail
    path('product/<str:id>', views.Product_detail, name='product_detail'),

    path('accounts/', views.Account_details, name='accounts'),

    path('ferthosi/', views.Ferthosi, name='ferthosi'),
    path('payment/', views.payment_view, name='payment'),

    path('bikash-payment/', views.bikash_payment_view, name='bikash_payment'),
    path('payment-request/', views.payment_request_view, name='payment_request'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment-confirmation/', views.payment_confirmation_view, name='payment_confirmation'),
    path('submit-payment-request/', views.submit_payment_request, name='submit_payment_request'),
              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E_shop/app/urls.py
from django.urls import path

# Views
from app.views import add_to_cart
from app.views import increase_cart_item
from app.views import decrease_cart_item
from app.views import remove_form_cart
from app.views import ChartProductListView
from app.views import check_out
from app.views import payment
from app.views import complete_payment
from app.views import purchase
from app.views import MyOrderListView

app_name = 'app'



# manage order
urlpatterns = [
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('cart-details/', ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/', increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/', decrease_cart_item, name='decrease_cart'),
    # path('my-order/', manage_order.MyOrderListView.as_view(),name="my_order"),
]

urlpatterns += [
    path('checkout/', check_out, name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-success/', complete_payment, name='payment_success'),
    path('purchase/<val_id>/<tran_id>/', purchase, name='purchase'),
    path('my-order/', MyOrderListView.as_view(),name="my_order"),
]

E_shop/templates/cart/cart_detail.html
{% extends 'master.html' %}
{% load cart_tag %}
{% block body %}

<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="#">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
					{% for item in chart_items %}
						<tr>
							<td class="cart_product">
								<a href=""><img src="{{item.items.image.url}}" style="height:20px;width:auto;" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{item.items.name}}</a></h4>

							</td>
							<td class="cart_price">
								<p>৳{{item.items.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href="{% url 'app:increase_cart' item.items.id %}"> + </a> 
									<input class="cart_quantity_input" type="text" name="quantity" value="{{item.quentity}}" autocomplete="off" size="2">
									<a class="cart_quantity_down" href="{% url 'app:decrease_cart' item.items.id %}"> - </a>
								</div>
							</td> 
							<td class="cart_total">
								<p class="cart_total_price">৳{{item.get_total}}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href="{% url 'app:decrease_cart' item.items.id %}"><i class="fa fa-times"></i></a>
							</td>
						</tr>
					<a href="{% url 'cart_clear' %}">Clear Cart</a>
						{% endfor %}

					</tbody>
					<tfoot>
						<td>

						</td>
						<td>

						</td>
						<td>
							<hr>
							<h4>Sub Total </h4>
						</td>
						<td>

						</td>
						<td>
							<hr>
							<h3> {{total_price}}</h3>
						</td>
					</tfoot>
				</table>
			</div>
		<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" style="float:right"> Check Out</button>-->
		<a class="btn btn-primary" href="{% url 'app:checkout' %}" >Checkout</a>

		</div>
	</section> <!--/#cart_items-->
<br>








{% endblock %}