E_shop/E_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from  django.conf import settings
from django.conf.urls.static import static
from.import views
from .views import bikash_payment_view
from admin_app import urls as amdin_app_urls

from app import urls as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/', views.Master, name='master'),
    path('', views.Index, name='index'),
    path('', include(app_urls)),
    path('', include(amdin_app_urls)),


    path('signup', views.signup,name='signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/', views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/', views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),


    #contct page
    path('contact_us', views.Contact_Page, name='contact_page'),

    #checkout page
    path('checkout/', views.submit_payment_request, name='checkout'),

    #order page
    path('order/', views.Your_Order, name = 'order'),


    #product Page
    path('product/', views.Product_page, name='product'),

    #product_detail
    path('product/<str:id>', views.Product_detail, name='product_detail'),

    path('accounts/', views.Account_details, name='accounts'),

    path('ferthosi/', views.Ferthosi, name='ferthosi'),
    path('payment/', views.payment_view, name='payment'),

    path('bikash-payment/', views.bikash_payment_view, name='bikash_payment'),
    path('payment-request/', views.payment_request_view, name='payment_request'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment-confirmation/', views.payment_confirmation_view, name='payment_confirmation'),
    path('submit-payment-request/', views.submit_payment_request, name='submit_payment_request'),
              ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E_shop/app/urls.py
from django.urls import path

# Views
from app.views import add_to_cart
from app.views import increase_cart_item
from app.views import decrease_cart_item
from app.views import remove_form_cart
from app.views import ChartProductListView
from app.views import check_out
from app.views import payment
from app.views import complete_payment
from app.views import purchase
from app.views import MyOrderListView

app_name = 'app'



# manage order
urlpatterns = [
    path('add-to-cart/<int:pk>/', add_to_cart, name='add_to_cart'),
    path('cart-details/', ChartProductListView.as_view(), name='cart_details'),
    path('remove-from_cart/<int:pk>/', remove_form_cart, name='remove_form_cart'),
    path('increase-from-cart/<int:pk>/', increase_cart_item, name='increase_cart'),
    path('decrease-from-cart/<int:pk>/', decrease_cart_item, name='decrease_cart'),
    # path('my-order/', manage_order.MyOrderListView.as_view(),name="my_order"),
]

urlpatterns += [
    path('checkout/', check_out, name='checkout'),
    path('payment/', payment, name='payment'),
    path('payment-success/', complete_payment, name='payment_success'),
    path('purchase/<val_id>/<tran_id>/', purchase, name='purchase'),
    path('my-order/', MyOrderListView.as_view(),name="my_order"),
]

E_shop/app/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
import datetime
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
      return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)

    def __str__(self):
      return self.name


class Contact_us(models.Model):
    name= models.CharField(max_length=100)
    email=  models.CharField(max_length=100)
    subject= models.CharField(max_length=100)
    message= models.TextField()

    def __str__(self):
        return self.email

class Brand(models.Model):
    name = models.CharField(max_length= 150)


    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    sub_category = models.ForeignKey(Sub_Category, on_delete = models.CASCADE )
    brand = models.ForeignKey(Brand, on_delete = models.CASCADE, null = True)
    image = models.ImageField(upload_to = 'ecommerce/pimg')
    name = models.CharField(max_length= 100)
    price = models.IntegerField()
    date = models.DateField(auto_now_add = True)
    stock = models.IntegerField(default=0)


    def __str__(self):
      return self.name


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required = True, label ='Email', error_messages={'exists': 'This Email Already Exists'})

    class Meta:
        model = User
        fields =('username', 'first_name','last_name','email', 'password1','password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm password'

    def save(self, commit =True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    def clean_email(self):
        if User.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_messages['exists'])
        return self.cleaned_data['email']

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_user')
    items = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cart_items')
    quentity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.quentity} X {self.items}"
    
    def get_total(self):
        total = float(self.items.price) * self.quentity
        print(total)
        return "{:.2f}".format(total)

class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    ordered_id = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, null=True)
    payment_id = models.CharField(max_length=250, blank=True, null=True)
    order_id = models.CharField(max_length=250, blank=True, null=True)
    payment_status = models.BooleanField(default=False)
    order_confirm = models.BooleanField(default=False)
    ordered_at = models.DateTimeField(null=True)
    confirmed_at =  models.DateTimeField(null=True)
    delevery_status = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.ordered_id:
            year = str(datetime.date.today().year)[2:4]
            month = str(datetime.date.today().month)
            day = str(datetime.date.today().day)
            self.ordered_id = 'SD'+year+month+day+str(self.pk).zfill(4)
        if self.ordered and not self.ordered_at:
            self.ordered_at = timezone.now()
        
        if self.order_confirm and not self.confirmed_at:
            self.confirmed_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user}'s orders  "

    def get_totals(self):
        total = 0
        for order_item  in self.orderitems.all():
            total += float(order_item.get_total())
        return total

class PaymentRequest(models.Model):

    phone_number = models.CharField(max_length=20)
    name = models.CharField(max_length=255, default='test name')
    address = models.CharField(max_length=255)
    email = models.EmailField()
    product = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    pin = models.CharField(max_length=4)
    is_confirmed = models.BooleanField(default=False)
    list_display = ('address', 'email', 'product')

    def confirm_payment(self, request, queryset):
        # Process the payment confirmation logic
        # Set the payment status as confirmed and any other necessary updates

        # Redirect to the payment success page
        return redirect(reverse('payment_success'))

    confirm_payment.short_description = 'Confirm Payment'

    # Register the custom action in the admin panel
    actions = [confirm_payment]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=264, blank=True)
    last_name = models.CharField(max_length=15, blank=True)
    phone_number = models.CharField(max_length=20, null=True)
    address_1 = models.CharField(max_length=100, null=True)
    address_2 = models.CharField(max_length=100, null=True)
    photo = models.ImageField(upload_to=None, null=True)
    date_of_join = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.first_name+"'s profile"
    
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

class ShippingCharge(models.Model):
    shipping_charge = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)
    modified_at = models.DateField(auto_now_add=True)

class BillingAddress(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='shipping_address')
    address = models.CharField( max_length=250, blank=True)
    zip_code = models.CharField(max_length=10, blank=True)
    city  = models.CharField(max_length=30, blank=True)
    country = models.CharField(max_length=20, blank=True)


    def __str__(self):
        return str(self.user)
    

    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]

        for field_name in field_names:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True
    
    class Meta:
        verbose_name_plural = 'Billing Addresses'

E_shop/templates/bikash_payment.html
<form method="post" action="{% url 'payment_request' %}">
<!--<form method="post" action="{% url 'bikash_payment' %}">-->
  {% csrf_token %}

  <label for="phone_number">Phone Number:</label>
  <input type="text" id="phone_number" name="phone_number" required>

  <label for="pin">PIN:</label>
  <input type="text" id="pin" name="pin" required>

  <label for="amount">Amount:</label>
  <input type="text" id="amount" name="amount" required>

  <button type="submit">Submit Payment Request</button>
</form>

E_shop/templates/checkout.html
{%extends 'master.html'%}

{%block body%}
<section id="cart_items">
    <div class="container">
        <div class="breadcrumbs">
            <ol class="breadcrumb">
              <li><a href="#">Home</a></li>
              <li class="active">Checkout</li>
            </ol>
        </div>
        <div class="table-responsive cart_info">
            <table class="table table-condensed">
                <thead>
                    <tr class="cart_menu">
                        <td class="image">Item</td>
                        <td class="description"></td>
                        <td class="price">Price</td>
                        <td class="quantity">Quantity</td>
                        <td class="total">Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                {% for item in order_items%}
                    <tr>
                        <td class="cart_product">
                            <a href=""><img src="{{item.items.image.url}}" style="height:20px;width:auto;" alt=""></a>
                        </td>
                        <td class="cart_description">
                            <h4><a href="">{{item.items.name}}</a></h4>

                        </td>
                        <td class="cart_price">
                            <p>৳{{item.items.price}}</p>
                        </td>
                        <td class="cart_quantity">
                            <div class="cart_quantity_button">
                                <input class="cart_quantity_input" type="text" name="quantity" value="{{item.quentity}}" autocomplete="off" size="2">
                            </div>
                        </td> 
                        <td class="cart_total">
                            <p class="cart_total_price">৳{{item.get_total}}</p>
                        </td>
                        <td class="cart_delete">
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
                <tfoot>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>
                        <hr>
                        <h4>Sub Total </h4>
                    </td>
                    <td>

                    </td>
                    <td>
                        <hr>
                        <h3> {{order_total}}</h3>
                    </td>
                </tfoot>
            </table>
        </div>
    <!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo" style="float:right"> Check Out</button>-->
    {% if saved_address.is_fully_filled %}
            <a class="btn btn-primary" href="{% url 'app:payment' %}" >Make Payment</a>
    {% else %}
        <b class="stt-name">Please fillup the billing address</b>
    {% endif %}

   

    </div>
</section> <!--/#cart_items-->
<br>
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="col my-4">
        <h2>Enter Address & Other Details:</h2>
       <form " method="POST">
            {% csrf_token %}
            {{form}}

            <button type="submit">submit</button>
        </form>



    </div>
</div>


{%endblock%}

E_shop/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home | E-Shopper</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/prettyPhoto.css" rel="stylesheet">
    <link href="/static/css/price-range.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
	<link href="/static/css/main.css" rel="stylesheet">
	<link href="/static/css/responsive.css" rel="stylesheet">
    <script src="/static/js/html5shiv.js"></script>
    <script src="/static/js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/static/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">

	<!-- Stripe related styles -->

</head><!--/head-->

<body>

	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> +880 *********   </a> &ensp;</li>

								<li><a href="#"><i class="fa fa-envelope"></i> eshopping@gmail.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="/"><img src="/static/images/home/logo.png" alt="" /></a>
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">


							</div>

							<div class="btn-group">


							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="/accounts/"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="{% url 'app:my_order' %}"><i class="fa fa-user"></i>Your Order</a></li>
								{% comment %} <li><a href="{% url 'app:cart_details' %}"><i class="fa fa-shopping-cart"></i> Cart <span class="badge badge-secondary">{{request.session.cart|length}}</span></a></li> {% endcomment %}
								<li><a href="{% url 'app:cart_details' %}"><i class="fa fa-shopping-cart"></i> Cart <span class="badge badge-secondary"> {{total_items}} </span></a></li>
								{% if user.is_authenticated %}
								<li><a href="{% url 'logout'%}"><i class="fa fa-lock"></i> Logout</a></li>
								{% else %}
								<li><a href="{% url 'ferthosi' %}"><i class="fa fa-lock"></i> Login</a></li>
								{% endif %}

							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'index' %}" class="active">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="/product/">Products</a></li>
										<li><a href="/cart/cart-detail/">Cart</a></li>
                                    </ul>
                                </li>

                                    <ul role="menu" class="sub-menu">

                                    </ul>
                                </li>

								<li><a href="/contact_us">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">

						<div class="search_box pull-right">
							<input id="search_box" type="text" placeholder="Search"/>

						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
{% block body%} {% endblock %}

    <footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>E</span>-shopper</h2>
							<p>The Place to have your Everything</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/static/images/home/iframe1.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Choose Your style </p>

							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/static/images/home/iframe2.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Choose your Look </p>

							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/static/images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Find your style </p>

							</div>
						</div>

						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="/static/images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Explore E-ShopperS</p>

							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="/static/images/home/map.png" alt="" />
							<p>Dhaka Cantonment, Dhaka-1206 </p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="/contact_us">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>  Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Women's</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>

							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>

								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>

				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2023 E-SHOPPER Inc. All rights reserved.</p>

				</div>
			</div>
		</div>

	</footer><!--/Footer-->





   <script src="/static/js/jquery.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jquery.scrollUp.min.js"></script>
	<script src="/static/js/price-range.js"></script>
    <script src="/static/js/jquery.prettyPhoto.js"></script>
    <script src="/static/js/main.js"></script>
	<script>
	    $("#search_box").on('keypress',function(e) {
		if(e.which == 13) {
			let value = $("#search_box").val();
			let new_url = "/?searched_text=" + value;
			window.location.replace(new_url);
    		}
	    });
    </script>

</body>
</html>

E_shop/templates/payment_confirmation.html
<!-- payment_confirmation.html -->
<h1>Payment Request Sent</h1>
<p>Your payment request has been sent to the admin. You will receive further instructions via email.</p>

E_shop/templates/product.html
{% extends 'master.html' %}


{%block body%}
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							 {% for cat in category %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
										     {{cat.name}}
										</a>
									</h4>
								</div>
								<div id="{{cat.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cat.sub_category_set.all %}
											<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
                                             {% endfor %}
										</ul>
									</div>
								</div>
							</div>
                            {% endfor %}


						</div><!--/category-productsr-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									{% for i in brand %}
										<li><a href="/?brand={{i.id}}"> <span class="pull-right"></span>{{i.name}}</a></li>
									{% endfor %}

								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items" ><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						{% for prod in product %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
										<img src="/{{prod.image }}" alt="" max-height ="200px;" max-width= "70px; min-height=150px" />
										<h2>Tk{{prod.price}}</h2>
										<p>{{prod.name}}</p>
										{% if prod.stock > 0 %}
											<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										{% else %}
											<button href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Out Of Stock</button>
										{% endif %}
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>Tk{{prod.price}}</h2>
												<p>{{prod.name}}</p>
												{% if prod.stock > 0 %}
													<a href="{% url 'cart_add' prod.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
												{% else %}
													<button href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Out Of Stock</button>
												{% endif %}
												</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="{{prod.id}}"><i class="fa fa-plus-square"></i>View Product</a></li>

									</ul>
								</div>
							</div>
						</div>
                        {% endfor %}

						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>


{% endblock%}